#!/bin/sh

KAWA_COLOR=0
KAWA_OUT="a.out"
KAWA_VERSION="0.5"
KAWA_AUTO_RUN=0;
KAWAP=kawap

KAWA_COLOR_GREEN="1;32"
KAWA_COLOR_RED="1;31"
KAWA_COLOR_MAGENTA="1;35"
KAWA_COLOR_WHITE="1;37"
KAWA_COLOR_YELLOW="1;33"

color_begin(){
	if [ $KAWA_COLOR -eq 1 ]; then
		echo -n "\033[$1m"
	fi
}

color_end(){
	if [ $KAWA_COLOR -eq 1 ]; then
		echo -n "\033[0m"
	fi
}

version(){
	color_begin $KAWA_COLOR_WHITE
	echo -n "version "
	color_begin $KAWA_COLOR_YELLOW
	echo $KAWA_VERSION
	color_end
	if [ ! "$1" = "false" ]; then
	  exit 0;
	fi
}

usage() {
	color_begin $KAWA_COLOR_WHITE
	echo "Usage: "
	color_begin $KAWA_COLOR_GREEN
	echo -n "\tkawac "
	color_begin $KAWA_COLOR_WHITE
	echo -n "["
	color_begin $KAWA_COLOR_YELLOW
	echo -n "-h"
	color_begin $KAWA_COLOR_WHITE
	echo -n "] | ["
	color_begin $KAWA_COLOR_YELLOW
	echo -n "-v"
	color_begin $KAWA_COLOR_WHITE
	echo -n "] | ["
	color_begin $KAWA_COLOR_YELLOW
	echo -n "-c"
	color_begin $KAWA_COLOR_WHITE
	echo -n "] ["
	color_begin $KAWA_COLOR_YELLOW
	echo -n "-r"
	color_begin $KAWA_COLOR_WHITE
	echo -n "] ["
	color_begin $KAWA_COLOR_YELLOW
	echo -n "-o"
	color_begin $KAWA_COLOR_MAGENTA
	echo -n " output_name"
	color_begin $KAWA_COLOR_WHITE
	echo -n "] "
	color_begin $KAWA_COLOR_YELLOW
	echo -n "-m"
	color_begin $KAWA_COLOR_MAGENTA
	echo " KAWA_FILES\n"
	color_end

	version "false"
	echo -n "\n"
	color_begin $KAWA_COLOR_WHITE
	echo "OPTIONS:"
	
	color_begin $KAWA_COLOR_YELLOW
	echo -n "\th"
	color_begin $KAWA_COLOR_WHITE
	echo "            : affiche l'aide"
	echo -n "\n"
	
	color_begin $KAWA_COLOR_YELLOW
	echo -n "\tv"
	color_begin $KAWA_COLOR_WHITE
	echo "            : affiche la version"
	echo -n "\n"
	
	color_begin $KAWA_COLOR_YELLOW
	echo -n "\tc"
	color_begin $KAWA_COLOR_WHITE
	echo "            : affiche la sortie en couleur"
	echo -n "\n"
	
	color_begin $KAWA_COLOR_YELLOW
	echo -n "\tr"
	color_begin $KAWA_COLOR_WHITE
	echo "            : active le mode autorun qui lance le programme compilé à la fin"
	echo "\t               de la compilation"
	echo -n "\n"

	color_begin $KAWA_COLOR_YELLOW
	echo -n "\to"
	color_begin $KAWA_COLOR_MAGENTA
	echo -n " output_name"
	color_begin $KAWA_COLOR_WHITE
	echo ": définit le nom de l'exécutable"
	echo -n "\n"

	color_begin $KAWA_COLOR_YELLOW
	echo -n "\tm"
	color_begin $KAWA_COLOR_MAGENTA
	echo -n " KAWA_FILES"
	color_begin $KAWA_COLOR_WHITE
	echo " : lance la compilation des fichiers KAWA_FILES en mode monolitique"
	echo -n "\n"

	color_begin $KAWA_COLOR_RED
	echo "\n\nIMPORTANT"
	color_begin $KAWA_COLOR_MAGENTA
	echo "\t Il est important de finir la commande par l'ensemble des fichiers à compiler."
	echo "\tAutrement, les options qui suivent seront vues comme des noms de fichiers"
	color_end
	exit 0
}



check(){
	if [ ! $? = 0 ];
	then
		color_begin $KAWA_COLOR_RED
		echo $1
		color_end
		exit $?
	fi
}

remove(){
	for i in $*; do
		if [ -f $1 ]; then
			rm $1
		fi
	done	
}

monoc(){
	shift $((OPTIND-2))
	KAWA_SRC=""
	for kawaSrc in $*; do
		EXTENSION=`echo "$kawaSrc" | cut -d'.' -f2`
		if [ $EXTENSION = "kawa" ]; then
			if [ ! -f "$kawaSrc" ]; then
				color_begin $KAWA_COLOR_WHITE
				echo -n $kawaSrc
				color_begin $KAWA_COLOR_RED
				echo " est introuvable"
				color_end
			else
				KAWA_SRC="$KAWA_SRC $kawaSrc"
			fi
		else
			color_begin $KAWA_COLOR_YELLOW
			echo -n "le fichier "
			color_begin $KAWA_COLOR_WHITE
			echo -n $kawaSrc
			color_begin $KAWA_COLOR_YELLOW
			echo -n " doit avoir l'extention "
			color_begin $KAWA_COLOR_WHITE
			echo ".kawa"
			color_end
		fi
	done
	if [ "$KAWA_SRC" = "" ]; then
		color_begin $KAWA_COLOR_MAGENTA
		echo "Aucun fichier à compiler"
		color_end
		exit
	else
		color_begin $KAWA_COLOR_WHITE
		echo "Compilation en mode monolithique"
		color_end
	fi
		
	remove program.ll
	remove program.s
	remove $KAWA_OUT

	if [ -f ./kawap ]; then
		./kawap -m $KAWA_SRC
	else
		kawap -m $KAWA_SRC
	fi

	check "kawap: la compilation a échouée"
	
	KAWA_LLC="llc"
	if [ ! -f /usr/bin/llc ]; then
		if [ -f /usr/bin/llc-3.5 ]; then
		  KAWA_LLC="llc-3.5"
		else
		  color_begin $KAWA_COLOR_RED
		  echo -n "Les composants suivant sont introuvables: "
		  color_begin $KAWA_COLOR_WHITE
		  echo "llc, llc-3.5"
		  color_end
		  exit 1
		fi
	  
	fi
	
	$KAWA_LLC program.ll
	check "llc: la compilation a échouée" 
	
	gcc program.s -o $KAWA_OUT
	check "gcc: la compilation a échouée"

	remove program.ll 
	remove program.s
	
	color_begin $KAWA_COLOR_GREEN
	echo "Compilation réussie: $KAWA_SRC"
	color_begin $KAWA_COLOR_YELLOW
	echo "Executable: $KAWA_OUT"
	color_end
	if [ $KAWA_AUTO_RUN -eq 1 ]; then
		color_begin $KAWA_COLOR_WHITE
		echo "Lancement du programme:\n"
		color_end
		./$KAWA_OUT
	fi
	exit $?
}



if [ ! -f ./$KAWAP ]; then
	if [ -f /usr/bin/kawa/$KAWAP ]; then
		KAWAP="/usr/bin/kawa/kawap"
	else
		echo "Installez kawap \nmake install"
		exit 0
	fi
fi

if [ $# = 0 ];
then
	usage
fi

while getopts cvro:m:h opts; do
 case ${opts} in
  c) KAWA_COLOR=1;;
  v) version;;
  r) KAWA_AUTO_RUN=1;;
  o) KAWA_OUT=$OPTARG;;
  m) monoc $@;;
  h) usage;;
 esac
done
# si aucune option n'a été renseignée malgrès la présence de flag
if [ $OPTIND -le 2 ]; then
	usage
fi

exit 0